making kind as internal network
Signed-off-by: Jonsy13 <vedant.shrotria@chaosnative.com>

diff --git a/build/air-gapped/Dockerfile b/build/air-gapped/Dockerfile
--- a/build/air-gapped/Dockerfile
+++ b/build/air-gapped/Dockerfile
@@ -2,7 +2,7 @@ FROM alpine:3.15
 
 WORKDIR /air-gapped-kind
 
-RUN apk add --no-cache ca-certificates
+RUN apk add --no-cache ca-certificates openssh-client
 
 # set up nsswitch.conf for Go's "netgo" implementation (which Docker explicitly uses)
 # - https://github.com/docker/docker-ce/blob/v17.09.0-ce/components/engine/hack/make.sh#L149
@@ -10,41 +10,41 @@ RUN apk add --no-cache ca-certificates
 # - docker run --rm debian:stretch grep '^hosts:' /etc/nsswitch.conf
 RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf
 
-ENV DOCKER_VERSION 20.10.12
+ENV DOCKER_VERSION 20.10.7
 # TODO ENV DOCKER_SHA256
 # https://github.com/docker/docker-ce/blob/5b073ee2cf564edee5adca05eee574142f7627bb/components/packaging/static/hash_files !!
 # (no SHA file artifacts on download.docker.com yet as of 2017-06-07 though)
 
 RUN set -eux; \
-	\
-	apkArch="$(apk --print-arch)"; \
-	case "$apkArch" in \
-		'x86_64') \
-			url='https://download.docker.com/linux/static/stable/x86_64/docker-20.10.12.tgz'; \
-			;; \
-		'armhf') \
-			url='https://download.docker.com/linux/static/stable/armel/docker-20.10.12.tgz'; \
-			;; \
-		'armv7') \
-			url='https://download.docker.com/linux/static/stable/armhf/docker-20.10.12.tgz'; \
-			;; \
-		'aarch64') \
-			url='https://download.docker.com/linux/static/stable/aarch64/docker-20.10.12.tgz'; \
-			;; \
-		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;; \
-	esac; \
-	\
-	wget -O docker.tgz "$url"; \
-	\
-	tar --extract \
-		--file docker.tgz \
-		--strip-components 1 \
-		--directory /usr/local/bin/ \
-	; \
-	rm docker.tgz; \
-	\
-	dockerd --version; \
-	docker --version
+  \
+  apkArch="$(apk --print-arch)"; \
+  case "$apkArch" in \
+    'x86_64') \
+      url='https://download.docker.com/linux/static/stable/x86_64/docker-20.10.7.tgz'; \
+      ;; \
+    'armhf') \
+      url='https://download.docker.com/linux/static/stable/armel/docker-20.10.7.tgz'; \
+      ;; \
+    'armv7') \
+      url='https://download.docker.com/linux/static/stable/armhf/docker-20.10.7.tgz'; \
+      ;; \
+    'aarch64') \
+      url='https://download.docker.com/linux/static/stable/aarch64/docker-20.10.7.tgz'; \
+      ;; \
+    *) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;; \
+  esac; \
+  \
+  wget -O docker.tgz "$url"; \
+  \
+  tar --extract \
+    --file docker.tgz \
+    --strip-components 1 \
+    --directory /usr/local/bin/ \
+  ; \
+  rm docker.tgz; \
+  \
+  dockerd --version; \
+  docker --version
 
 COPY build/air-gapped/modprobe.sh /usr/local/bin/modprobe
 COPY build/air-gapped/docker-entrypoint.sh /usr/local/bin/
@@ -60,44 +60,43 @@ RUN mkdir /certs /certs/client && chmod 1777 /certs /certs/client
 
 # https://github.com/docker/docker/blob/master/project/PACKAGERS.md#runtime-dependencies
 RUN set -eux; \
-	apk add --no-cache \
-		btrfs-progs \
-		e2fsprogs \
-		e2fsprogs-extra \
-		ip6tables \
-		iptables \
-		openssl \
-		shadow-uidmap \
-		xfsprogs \
-		xz \
+  apk add --no-cache \
+    btrfs-progs \
+    e2fsprogs \
+    e2fsprogs-extra \
+    ip6tables \
+    iptables \
+    openssl \
+    shadow-uidmap \
+    xfsprogs \
+    xz \
 # pigz: https://github.com/moby/moby/pull/35697 (faster gzip implementation)
-		pigz \
-	; \
+    pigz \
+  ; \
 # only install zfs if it's available for the current architecture
 # https://git.alpinelinux.org/cgit/aports/tree/main/zfs/APKBUILD?h=3.6-stable#n9 ("all !armhf !ppc64le" as of 2017-11-01)
 # "apk info XYZ" exits with a zero exit code but no output when the package exists but not for this arch
-	if zfs="$(apk info --no-cache --quiet zfs)" && [ -n "$zfs" ]; then \
-		apk add --no-cache zfs; \
-	fi
+  if zfs="$(apk info --no-cache --quiet zfs)" && [ -n "$zfs" ]; then \
+    apk add --no-cache zfs; \
+  fi
 
 # TODO aufs-tools
 
 # set up subuid/subgid so that "--userns-remap=default" works out-of-the-box
 RUN set -eux; \
-	addgroup -S dockremap; \
-	adduser -S -G dockremap dockremap; \
-	echo 'dockremap:165536:65536' >> /etc/subuid; \
-	echo 'dockremap:165536:65536' >> /etc/subgid
+  addgroup -S dockremap; \
+  adduser -S -G dockremap dockremap; \
+  echo 'dockremap:165536:65536' >> /etc/subuid; \
+  echo 'dockremap:165536:65536' >> /etc/subgid
 
 # https://github.com/docker/docker/tree/master/hack/dind
 ENV DIND_COMMIT 42b1175eda071c0e9121e1d64345928384a93df1
 
 RUN set -eux; \
-	wget -O /usr/local/bin/dind "https://raw.githubusercontent.com/docker/docker/${DIND_COMMIT}/hack/dind"; \
-	chmod +x /usr/local/bin/dind
+  wget -O /usr/local/bin/dind "https://raw.githubusercontent.com/docker/docker/${DIND_COMMIT}/hack/dind"; \
+  chmod +x /usr/local/bin/dind
 
 COPY build/air-gapped/dockerd-entrypoint.sh /usr/local/bin/
-RUN chmod +x /usr/local/bin/dockerd-entrypoint.sh
 
 VOLUME /var/lib/docker
 EXPOSE 2375 2376
